# NumPy Basics

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides high-performance multidimensional array objects and tools for working with them.

In [1]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80])
print(arr,type(arr))

[10 20 30 40 50 60 70 80] <class 'numpy.ndarray'>


In [2]:
arr[-1]

80

In [3]:
arr[1]

20

In [4]:
arr[:]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [5]:
arr[::]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [6]:
arr[1:-1:2]

array([20, 40, 60])

In [7]:
arr*=10

In [8]:
arr

array([100, 200, 300, 400, 500, 600, 700, 800])

## array is homogenius ,supports only one data type

In [9]:
# Difference between list and arrray
arr1=np.array([10,20,30])*5
print(arr1)

[ 50 100 150]


In [10]:
arr=[10,20,45]*5
print(arr)


[10, 20, 45, 10, 20, 45, 10, 20, 45, 10, 20, 45, 10, 20, 45]


In [11]:
# list takes more memory array takes less

In [12]:
l=[[1,2,3],[12,34]]
l

[[1, 2, 3], [12, 34]]

In [13]:
arr=np.array([[1,2,3],[4,5,6]],ndmin=2)
print(arr)

[[1 2 3]
 [4 5 6]]


In [14]:
arr.shape

(2, 3)

## Range  
### It generates each value one by one when the loop runs, which makes it memory efficient

In [15]:

# How for loop range works : generates and adds all or generates and adds one by one
print(range(1,11))

range(1, 11)


In [16]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [17]:
array_l=list(range(1,11))
print(array_l)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


## arange()

In [18]:
arr=np.arange(1,10,3)
# EXclusive ,
print(arr)

[1 4 7]


# linspace()

In [19]:
np.linspace(1,10,5)# inclusive 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### 

### Indexing and slicing

In [21]:
arr =np.array([[1,2,3],[10,20,14],[90,30,4],[33,44,24],[34,24,67],[9,3,5]])
l1=[1,2,3,4,5,6,7,8,9]

In [22]:
print(arr)
print(l1)

[[ 1  2  3]
 [10 20 14]
 [90 30  4]
 [33 44 24]
 [34 24 67]
 [ 9  3  5]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [75]:
print(arr[1][0])
print(l1[1])

10
5


In [24]:
print(arr[-1])
print(l1[-1])

[9 3 5]
9


In [25]:
print(arr[::-1])
print(l1[::-1])

[[ 9  3  5]
 [34 24 67]
 [33 44 24]
 [90 30  4]
 [10 20 14]
 [ 1  2  3]]
[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [26]:
print(arr[1::2])
print(l1[1::2])

[[10 20 14]
 [33 44 24]
 [ 9  3  5]]
[2, 4, 6, 8]


# Syntax:
    arrayname[row index,col index]
                '
                '

In [27]:
print(arr)

[[ 1  2  3]
 [10 20 14]
 [90 30  4]
 [33 44 24]
 [34 24 67]
 [ 9  3  5]]


In [28]:
arr[[4]]

array([[34, 24, 67]])

In [78]:
arr[[3,2,0]]

array([[33, 44, 24],
       [90, 30,  4],
       [ 1,  2,  3]])

In [30]:
arr[:,[2,1]]

array([[ 3,  2],
       [14, 20],
       [ 4, 30],
       [24, 44],
       [67, 24],
       [ 5,  3]])

In [31]:
arr[[0,1]][:,[2,1]]
# 3  2
# 14 20

array([[ 3,  2],
       [14, 20]])

In [32]:
print(arr)

[[ 1  2  3]
 [10 20 14]
 [90 30  4]
 [33 44 24]
 [34 24 67]
 [ 9  3  5]]


In [33]:
arr[[1,0]][:,[1,2]]
#20  14
#2   3

array([[20, 14],
       [ 2,  3]])

In [34]:
arr[[0,2]][:,[0,1]]
#1  2
#90 30

array([[ 1,  2],
       [90, 30]])

In [80]:
# 30 90
# 44 33
arr[[2,3]][:,[1,0]]

array([[30, 90],
       [44, 33]])

In [36]:
print(arr)

[[ 1  2  3]
 [10 20 14]
 [90 30  4]
 [33 44 24]
 [34 24 67]
 [ 9  3  5]]


In [37]:
arr[2:4,1:3]

array([[30,  4],
       [44, 24]])

# Random

In [81]:
rand_num=np.random.randint(1,20)
print(rand_num)

13


In [39]:
Count=0
while True:
   
    Count+=1
    n=int(input("Enter a Guess:"))
    if n==rand_num:
        print("Right right kii huu")
        print("Attemepts :",Count)
        break
    elif n>rand_num:
        print("Your guess is greter then Random number")
      
    elif n<rand_num:
        print("Your guess is lesser then Random number")
       

  

Your guess is lesser then Random number
Your guess is lesser then Random number
Your guess is lesser then Random number
Your guess is greter then Random number
Your guess is lesser then Random number
Your guess is greter then Random number
Your guess is greter then Random number
Your guess is greter then Random number
Right right kii huu
Attemepts : 9


# WORK to do this game and 
# define a mode funtion to get the most repeated number using unique function.

In [40]:
import numpy as np
l=['Stone','Paper','Scissor']
user_point=0
computer=0
count=0
Rand_SPS=np.random.choice(l)

while count<3:
    user=input("Enter Stone or Paper or Scissor")
    count+=1
    if user=='Stone' and Rand_SPS=='Paper':
        computer+=1
    elif user=="Stone" and Rand_SPS=='Scissor':
        user_point+=1
    elif user=="Stone" and Rand_SPS=="Stone":
        print("Tie")
    elif user=="Paper" and Rand_SPS=='Scissor':
        user_point+=1
    elif user=="Paper" and Rand_SPS=="Stone":
        user_point+1
    elif user=="Paper" and Rand_SPS=='Paper':
        print("Tie")
    elif user=="Scissor" and Rand_SPS=="Stone":
        computer+=1
    elif user=="Scissor" and Rand_SPS=="Paper":
        user_point+=1
    elif user=="Scissor" and Rand_SPS=="Scissor":
        print("Tie")
if user_point>computer:
    print("YOU WON !!!!!")  
    print(f" User Point:{user_point}\n Computer Point:{computer}")
else:
    print("Computer WON!!!!!")
    print(f" User Point:{user_point}\n Computer Point:{computer}")

YOU WON !!!!!
 User Point:3
 Computer Point:0


In [41]:
np.random.randint(1,100)

22

In [42]:
np.random.randint(1,100,5)

array([45, 39, 21, 83, 39])

In [43]:
arr1=np.random.randint(1,100,(2,5))
arr1

array([[ 2, 15, 97, 19, 42],
       [85, 21, 62,  6, 35]])

# Agg function

In [44]:
np.sum(arr1[:,[2]],axis=0)

array([159])

In [45]:
np.mean(arr1[[0,1],[2]],axis=0)

79.5

# Seed()

In [46]:
np.random.seed(1)
arr2=np.random.randint(1,100,(2,5))
arr2


array([[38, 13, 73, 10, 76],
       [ 6, 80, 65, 17,  2]])

In [47]:
np.unique(arr2)

array([ 2,  6, 10, 13, 17, 38, 65, 73, 76, 80])

In [48]:
arr3=np.array([1,2,3,2,1,2,3,1,2,3,1,2])
np.unique(arr3,return_counts=False)

array([1, 2, 3])

In [49]:
arr3=np.array([1,2,3,2,1,2,3,1,2,3,1,2])
np.unique(arr3,return_counts=True)

(array([1, 2, 3]), array([4, 5, 3], dtype=int64))

In [50]:
arr4=np.array([1,2,3,2,1,2,3,1,2,3,1,2,3,1,2,3,2,3,4,2,1,12,3,3,1,12,33,12,2,33])
unique_values,counts=np.unique(arr4,return_counts=True)


In [51]:
print(unique_values)
print(counts)

[ 1  2  3  4 12 33]
[7 9 8 1 3 2]


In [52]:



# def mode(unique_values, counts):
#     m = counts[0]   
#     i = 0           

#     for idx in range(len(counts)):
#         if counts[idx] > m:
#             m = counts[idx]
#             i = idx

#     print("Most Repeated value is:", unique_values[i])
#     print(f"Times it has repeated: {m}")




In [53]:

def mode(unique_values,counts):
    m=counts[0]
    i=0
    n=len(counts)
    for num in range(n-1):
        if counts[num]>m:
            m=counts[num]
            i=num 
    print(f"Times it has repeated:{m}")     
    print("Most Repeated value is:::",unique_values[i])
    
    

    


In [54]:
mode(unique_values,counts)

Times it has repeated:9
Most Repeated value is::: 2


# Python code Visualizer

In [55]:
l=[[1,2],[4,5],10]
# expected outcome->[1,2,4,5,10]

new=[]
for val in l:
    if type(val)==list:
        l1=[i for i in val]
        new= new + l1
    else:
        new.append(val)
print(new)





[1, 2, 4, 5, 10]


In [56]:
# new1=[]
# for val in l:
#     if type(val)==list:
#         l1=[i for i in val]
#         new1= new1 + l1
#         print(new1)
#         print(l1)

In [57]:
arr

array([[ 1,  2,  3],
       [10, 20, 14],
       [90, 30,  4],
       [33, 44, 24],
       [34, 24, 67],
       [ 9,  3,  5]])

In [58]:
arr.flatten()

array([ 1,  2,  3, 10, 20, 14, 90, 30,  4, 33, 44, 24, 34, 24, 67,  9,  3,
        5])

In [59]:
arr.shape

(6, 3)

# reshape

In [60]:
# arr 6x3
# arr.reshape(row,col)
arr.reshape(3,6)
arr.reshape(2,9)
arr.reshape(18,1)
arr.reshape(1,18)

array([[ 1,  2,  3, 10, 20, 14, 90, 30,  4, 33, 44, 24, 34, 24, 67,  9,
         3,  5]])

In [61]:
arr.reshape(-1)

array([ 1,  2,  3, 10, 20, 14, 90, 30,  4, 33, 44, 24, 34, 24, 67,  9,  3,
        5])

# resize
 # Resize updates the array reshape returns new array

In [62]:
arr.resize(6,3)

In [63]:
arr

array([[ 1,  2,  3],
       [10, 20, 14],
       [90, 30,  4],
       [33, 44, 24],
       [34, 24, 67],
       [ 9,  3,  5]])

In [64]:
x=np.array([10,20,30,40,50])
y=np.array([100,200,300,400,500])
#print(x)
X_mean=x.mean()
Y_mean=y.mean()
len(x)

    

5

In [65]:
Variance_X=0
Variance_Y=0

In [66]:

for val in x:
    Variance_X+=(val-X_mean)**2/len(x)


In [67]:

for val in y:
    Variance_Y+=(val-Y_mean)**2/len(y)

In [68]:
print(Variance_X)
print(Variance_Y)

200.0
20000.0


In [69]:
cov_sum=0
for i in range(len(x)):
    cov_sum+=(x[i]-X_mean)*(y[i]-Y_mean)
cov_xy=cov_sum/len(x)


In [70]:
print(cov_xy)

2000.0


In [71]:
var_X=np.sum((x-np.mean(x))**2)/len(x)
var_X

200.0

In [72]:
var_Y=np.sum((y-np.mean(y))**2)/len(y)
var_Y

20000.0

In [73]:
Cov_XY=np.sum((x-X_mean)*(y-Y_mean))/len(x)
Cov_XY

2000.0